# Machine learning within data science

## NUMPY: ARRAYS AND MATRICES

Test Code By <a href="https://www.facebook.com/peny.ismail.77">Peny Ismail</a> - <a href="https://github.com/peny77">Github</a>

### Create arrays

In [10]:
import numpy as np

data = [1,2,3,4,5]
arr1 = np.array(data)
data2= [range(1,5), range(5,9)]
arr2 = np.array(data2)
print('List ', data)
print('ID Array ', arr1)

List  [1, 2, 3, 4, 5]
ID Array  [1 2 3 4 5]


In [12]:
print('List of list ', data2)

List of list  [range(1, 5), range(5, 9)]


In [13]:
print('2D Array ', arr2)

2D Array  [[1 2 3 4]
 [5 6 7 8]]


In [14]:
print('Convert array back to list ', arr2)

Convert array back to list  [[1 2 3 4]
 [5 6 7 8]]


#### create special arrays

In [17]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [20]:
# 0 to 1 (inclusive) with 5 points
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [22]:
# 10^0 to 10^3 (inclusive) with 4 points
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

In [24]:
int_array = np.arange(5)
int_array

array([0, 1, 2, 3, 4])

In [26]:
float_array = int_array.astype(float)
float_array

array([0., 1., 2., 3., 4.])

### Examining arrays

In [29]:
arr1.dtype
arr2.dtype

dtype('int32')

In [30]:
arr2.ndim

2

In [31]:
arr2.shape

(2, 4)

In [34]:
# total number of elements
arr2.size

8

In [35]:
# size of first dimension (aka axis)
len(arr2)

2

### Reshaping

In [37]:
arr = np.arange(10, dtype=float).reshape((2,5))
print(arr.shape)

(2, 5)


In [38]:
print(arr.reshape(5,2))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


**Add an axis**

In [40]:
a = np.array([0,1])
a_kolom = a[:, np.newaxis]
print(a_kolom)
a_kolom = a[:,None]

[[0]
 [1]]


**Transpose**

In [42]:
print(a_kolom.T)

[[0 1]]


**Flatten: always returns a flat copy of the orriginal array**

In [49]:
arr_flate = arr.flatten()
arr_flate[0] = 99
print(arr_flate)

[99.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [50]:
print(arr)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


In [51]:
arr_flate = arr.ravel()
arr_flate[0] = 88
print(arr_flate)

[88.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [52]:
print(arr)

[[88.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


### Stack arrays

**Stack flat arrays in columns**

In [56]:
a = np.array([0,1])
b = np.array([2,3])

ab = np.stack((a,b)).T
print(ab)

[[0 2]
 [1 3]]


In [57]:
np.hstack((a[:, None], b[:, None]))

array([[0, 2],
       [1, 3]])

### Selection

**Single item**

In [59]:
arr = np.arange(10, dtype=float).reshape((2,5))
arr[0]

array([0., 1., 2., 3., 4.])

In [64]:
#row 0, column 3
arr[0,3] 

3.0

In [65]:
# alternative syntax
arr[0][3]

3.0

#### Slicing

Syntax:
> start:stop:step with start (default 0) stop (default last) step (default 1)

In [71]:
print(arr[0, :])
print(arr[:, 0])

[0. 1. 2. 3. 4.]
[0. 5.]


In [73]:
print(arr[:, :2])
print(arr[:, 2:])

[[0. 1.]
 [5. 6.]]
[[2. 3. 4.]
 [7. 8. 9.]]


In [74]:
arr2 = arr[:, 1:4]
print(arr2)

[[1. 2. 3.]
 [6. 7. 8.]]


**Slicing returns a view (not a copy)**

In [75]:
arr2[0,0] = 99
print(arr2)
print(arr)

[[99.  2.  3.]
 [ 6.  7.  8.]]
[[ 0. 99.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [76]:
print(arr[0, ::-1])

[ 4.  3.  2. 99.  0.]


### Fancy indexing: Integer or boolean array indexing

**Integer array indexing**

In [77]:
arr2 =arr[:, [1,2,3]]
print(arr2)

[[99.  2.  3.]
 [ 6.  7.  8.]]


In [78]:
arr2[0,0] = 44
print(arr2)

[[44.  2.  3.]
 [ 6.  7.  8.]]


In [79]:
arr

array([[ 0., 99.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.]])

**Boolean arrays indexing**

In [85]:
arr2 = arr[arr > 5]
print(arr2)
arr2[0] = 44
print(arr2)
print(arr)

[99.  6.  7.  8.  9.]
[44.  6.  7.  8.  9.]
[[ 0. 99.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]]


In [86]:
arr[arr > 5] = 0
print(arr)

[[0. 0. 2. 3. 4.]
 [5. 0. 0. 0. 0.]]


**Boolean arrays indexing continues**

In [88]:
nama = np.array(['iS','Nur','Musa','Fatimah','Ismail'])
print(nama)

['iS' 'Nur' 'Musa' 'Fatimah' 'Ismail']


In [89]:
nama == 'Fatimah'

array([False, False, False,  True, False])

In [90]:
nama[nama != 'Ismail']

array(['iS', 'Nur', 'Musa', 'Fatimah'], dtype='<U7')

In [91]:
(nama == 'Fatimah')|(nama == 'Ismail')

array([False, False, False,  True,  True])

In [93]:
nama[nama !='Musa'] = 'iS'
np.unique(nama)

array(['Musa', 'iS'], dtype='<U7')

### Vectorized operations

In [97]:
no = np.arange(5)
no

array([0, 1, 2, 3, 4])

In [98]:
no * 10

array([ 0, 10, 20, 30, 40])

In [100]:
no = np.sqrt(no)
no

array([0.        , 1.        , 1.18920712, 1.31607401, 1.41421356])

In [101]:
np.ceil(no)

array([0., 1., 2., 2., 2.])

In [102]:
np.isnan(no)

array([False, False, False, False, False])

In [103]:
no + np.arange(5)

array([0.        , 2.        , 3.18920712, 4.31607401, 5.41421356])

In [104]:
np.maximum(no, np.array([1,-2,3,-4,5]))

array([1.        , 1.        , 3.        , 1.31607401, 5.        ])

In [107]:
# Compute Euclidean distance between 2 vectors
vec1 = np.random.randn(10)
vec2 = np.random.randn(10)
dist = np.sqrt(np.sum((vec1 - vec2) ** 2))
dist

3.6562774425701403

In [118]:
# math and stats
rnd = np.random.randn(4,2) # random normals in 4x2 array
print(rnd)

[[ 0.70446861  1.47265592]
 [ 1.91211376  1.33164734]
 [ 1.41943876 -1.53361797]
 [ 0.92714748  0.41901939]]


In [119]:
rnd.mean()

0.8316091615793113

In [120]:
rnd.std()

0.9977371237382733

In [121]:
# index of minimum element
rnd.argmin()

5

In [122]:
rnd.sum()

6.6528732926344905

In [125]:
# sum of columns
rnd.sum(axis=0) 

array([4.96316861, 1.68970468])

In [126]:
# sum of rows
rnd.sum(axis=1)

array([ 2.17712453,  3.2437611 , -0.11417921,  1.34616687])

In [127]:
# methods for boolean arrays
(rnd > 0).sum() # counts number of positive values

7

In [128]:
# checks if any value is True
(rnd > 0).any()

True

In [129]:
# checks if all values are True
(rnd >0).all()

False

In [135]:
# random numbers
np.random.seed(12345)

In [136]:
np.random.rand(2,3)

array([[0.92961609, 0.31637555, 0.18391881],
       [0.20456028, 0.56772503, 0.5955447 ]])

In [137]:
np.random.randn(10)

array([ 0.09290788,  0.28174615,  0.76902257,  1.24643474,  1.00718936,
       -1.29622111,  0.27499163,  0.22891288,  1.35291684,  0.88642934])

In [140]:
# 10 randomly picked 0 or 1
np.random.randint(0, 2, 10)

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0])

### Broadcasting

#### Rules

In [141]:
a = np.array([[0, 0, 0],
             [10, 10, 10],
             [20, 20, 20],
             [30, 30, 30]])

b = np.array([0, 1, 2])

print(a+b)

[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


Shapes of operands A, B and result:

A_____________(2d array):______5 x 4
B_____________(1d array):__________1
Result________(2d array):______5 x 4

A_____________(2d array):______5 x 4
B_____________(1d array):__________4
Result________(2d array):______5 x 4

## PANDAS: DATA MANIPULATION

In [19]:
from __future__ import print_function
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Create DataFrame

In [20]:
kolom = ['nama', 'usia', 'kelamin', 'pekerjaan']

user1 = pd.DataFrame([['Ismail', 18, 'L', 'pelajar'],
                    ['Fatimah', 28, 'P', 'enginer']],
                    columns=kolom)
user1

nama  usia kelamin pekerjaan
0   Ismail    18       L   pelajar
1  Fatimah    28       P   enginer

In [21]:
user2 = pd.DataFrame([['Musa', 18, 'L', 'mahasiswa'],
                    ['Hidayah', 28, 'P', 'manager']],
                    columns=kolom)
user2

nama  usia kelamin  pekerjaan
0     Musa    18       L  mahasiswa
1  Hidayah    28       P    manager

In [108]:
user3 = pd.DataFrame(dict(nama=['Sulaiman', 'Julie', 'Widya', 'Cindy'],
                          usia=[30, 44, 24, 26], kelamin=['L', 'P', 'P', 'P'],
                          pekerjaan=['engineer', 'scientist', 'scientist', 'engineer']))
user3

nama  usia kelamin  pekerjaan
0  Sulaiman    30       L   engineer
1     Julie    44       P  scientist
2     Widya    24       P  scientist
3     Cindy    26       P   engineer

### Combining DataFrames

#### Concatenate DataFrame

In [109]:
user1.append(user2)

nama  usia kelamin  pekerjaan
0   Ismail    18       L    pelajar
1  Fatimah    28       P    enginer
0     Musa    18       L  mahasiswa
1  Hidayah    28       P    manager

In [110]:
user = pd.concat([user1, user2, user3])
print(user)

       nama  usia kelamin  pekerjaan
0    Ismail    18       L    pelajar
1   Fatimah    28       P    enginer
0      Musa    18       L  mahasiswa
1   Hidayah    28       P    manager
0  Sulaiman    30       L   engineer
1     Julie    44       P  scientist
2     Widya    24       P  scientist
3     Cindy    26       P   engineer


#### Join DataFrame

In [114]:
user4 = pd.DataFrame(dict(nama=['Jibril','Nur','Hilmy','Peny','Rindi','Arum','Agus'],
                         tinggi=[165, 180, 165, 170, 160, 166, 165]))
print(user4)

     nama  tinggi
0  Jibril     165
1     Nur     180
2   Hilmy     165
3    Peny     170
4   Rindi     160
5    Arum     166
6    Agus     165


Use intersection of keys from both frames

In [115]:
merge_inter = pd.merge(user, user4, on='nama')
print(merge_inter)

Empty DataFrame
Columns: [nama, usia, kelamin, pekerjaan, tinggi]
Index: []


In [116]:
users = pd.merge(user, user4, on='nama', how='outer')
print(users)

        nama  usia kelamin  pekerjaan  tinggi
0     Ismail  18.0       L    pelajar     NaN
1    Fatimah  28.0       P    enginer     NaN
2       Musa  18.0       L  mahasiswa     NaN
3    Hidayah  28.0       P    manager     NaN
4   Sulaiman  30.0       L   engineer     NaN
5      Julie  44.0       P  scientist     NaN
6      Widya  24.0       P  scientist     NaN
7      Cindy  26.0       P   engineer     NaN
8     Jibril   NaN     NaN        NaN   165.0
9        Nur   NaN     NaN        NaN   180.0
10     Hilmy   NaN     NaN        NaN   165.0
11      Peny   NaN     NaN        NaN   170.0
12     Rindi   NaN     NaN        NaN   160.0
13      Arum   NaN     NaN        NaN   166.0
14      Agus   NaN     NaN        NaN   165.0


### Reshaping by pivoting

> 'Unpivots' a DataFrame from wide format to long (stacked) format,

In [117]:
staked = pd.melt(users, id_vars='nama', var_name='variable', value_name='value')
print(staked)

        nama   variable      value
0     Ismail       usia         18
1    Fatimah       usia         28
2       Musa       usia         18
3    Hidayah       usia         28
4   Sulaiman       usia         30
5      Julie       usia         44
6      Widya       usia         24
7      Cindy       usia         26
8     Jibril       usia        NaN
9        Nur       usia        NaN
10     Hilmy       usia        NaN
11      Peny       usia        NaN
12     Rindi       usia        NaN
13      Arum       usia        NaN
14      Agus       usia        NaN
15    Ismail    kelamin          L
16   Fatimah    kelamin          P
17      Musa    kelamin          L
18   Hidayah    kelamin          P
19  Sulaiman    kelamin          L
20     Julie    kelamin          P
21     Widya    kelamin          P
22     Cindy    kelamin          P
23    Jibril    kelamin        NaN
24       Nur    kelamin        NaN
25     Hilmy    kelamin        NaN
26      Peny    kelamin        NaN
27     Rindi    kela

> 'pivots' a DataFrame from long (stacked) format to wide format

In [118]:
print(staked.pivot(index='nama', columns='variable', values='value'))

variable kelamin  pekerjaan tinggi usia
nama                                   
Agus         NaN        NaN    165  NaN
Arum         NaN        NaN    166  NaN
Cindy          P   engineer    NaN   26
Fatimah        P    enginer    NaN   28
Hidayah        P    manager    NaN   28
Hilmy        NaN        NaN    165  NaN
Ismail         L    pelajar    NaN   18
Jibril       NaN        NaN    165  NaN
Julie          P  scientist    NaN   44
Musa           L  mahasiswa    NaN   18
Nur          NaN        NaN    180  NaN
Peny         NaN        NaN    170  NaN
Rindi        NaN        NaN    160  NaN
Sulaiman       L   engineer    NaN   30
Widya          P  scientist    NaN   24


## Summarizing

In [119]:
users

nama  usia kelamin  pekerjaan  tinggi
0     Ismail  18.0       L    pelajar     NaN
1    Fatimah  28.0       P    enginer     NaN
2       Musa  18.0       L  mahasiswa     NaN
3    Hidayah  28.0       P    manager     NaN
4   Sulaiman  30.0       L   engineer     NaN
5      Julie  44.0       P  scientist     NaN
6      Widya  24.0       P  scientist     NaN
7      Cindy  26.0       P   engineer     NaN
8     Jibril   NaN     NaN        NaN   165.0
9        Nur   NaN     NaN        NaN   180.0
10     Hilmy   NaN     NaN        NaN   165.0
11      Peny   NaN     NaN        NaN   170.0
12     Rindi   NaN     NaN        NaN   160.0
13      Arum   NaN     NaN        NaN   166.0
14      Agus   NaN     NaN        NaN   165.0

In [120]:
type(users)

pandas.core.frame.DataFrame

In [121]:
users.head()

nama  usia kelamin  pekerjaan  tinggi
0    Ismail  18.0       L    pelajar     NaN
1   Fatimah  28.0       P    enginer     NaN
2      Musa  18.0       L  mahasiswa     NaN
3   Hidayah  28.0       P    manager     NaN
4  Sulaiman  30.0       L   engineer     NaN

In [122]:
users.tail()

nama  usia kelamin pekerjaan  tinggi
10  Hilmy   NaN     NaN       NaN   165.0
11   Peny   NaN     NaN       NaN   170.0
12  Rindi   NaN     NaN       NaN   160.0
13   Arum   NaN     NaN       NaN   166.0
14   Agus   NaN     NaN       NaN   165.0

In [123]:
users.index

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14], dtype='int64')

In [124]:
users.columns

Index(['nama', 'usia', 'kelamin', 'pekerjaan', 'tinggi'], dtype='object')

In [125]:
users.dtypes

nama          object
usia         float64
kelamin       object
pekerjaan     object
tinggi       float64
dtype: object

In [126]:
users.shape

(15, 5)

In [127]:
users.values

array([['Ismail', 18.0, 'L', 'pelajar', nan],
       ['Fatimah', 28.0, 'P', 'enginer', nan],
       ['Musa', 18.0, 'L', 'mahasiswa', nan],
       ['Hidayah', 28.0, 'P', 'manager', nan],
       ['Sulaiman', 30.0, 'L', 'engineer', nan],
       ['Julie', 44.0, 'P', 'scientist', nan],
       ['Widya', 24.0, 'P', 'scientist', nan],
       ['Cindy', 26.0, 'P', 'engineer', nan],
       ['Jibril', nan, nan, nan, 165.0],
       ['Nur', nan, nan, nan, 180.0],
       ['Hilmy', nan, nan, nan, 165.0],
       ['Peny', nan, nan, nan, 170.0],
       ['Rindi', nan, nan, nan, 160.0],
       ['Arum', nan, nan, nan, 166.0],
       ['Agus', nan, nan, nan, 165.0]], dtype=object)

In [128]:
users.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15 entries, 0 to 14
Data columns (total 5 columns):
nama         15 non-null object
usia         8 non-null float64
kelamin      8 non-null object
pekerjaan    8 non-null object
tinggi       7 non-null float64
dtypes: float64(2), object(3)
memory usage: 540.0+ bytes


### Columns selection

In [129]:
users['kelamin']

0       L
1       P
2       L
3       P
4       L
5       P
6       P
7       P
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
Name: kelamin, dtype: object

In [130]:
type(users['kelamin'])

pandas.core.series.Series

In [131]:
users.kelamin

0       L
1       P
2       L
3       P
4       L
5       P
6       P
7       P
8     NaN
9     NaN
10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
Name: kelamin, dtype: object

> select multiple columns

In [132]:
users[['usia','kelamin']]

usia kelamin
0   18.0       L
1   28.0       P
2   18.0       L
3   28.0       P
4   30.0       L
5   44.0       P
6   24.0       P
7   26.0       P
8    NaN     NaN
9    NaN     NaN
10   NaN     NaN
11   NaN     NaN
12   NaN     NaN
13   NaN     NaN
14   NaN     NaN

In [133]:
kolom_ku = ['nama','kelamin']
kolom_ku

['nama', 'kelamin']

In [134]:
users[kolom_ku]

nama kelamin
0     Ismail       L
1    Fatimah       P
2       Musa       L
3    Hidayah       P
4   Sulaiman       L
5      Julie       P
6      Widya       P
7      Cindy       P
8     Jibril     NaN
9        Nur     NaN
10     Hilmy     NaN
11      Peny     NaN
12     Rindi     NaN
13      Arum     NaN
14      Agus     NaN

In [135]:
type(users[kolom_ku])

pandas.core.frame.DataFrame

### Rows selection (basic)

In [136]:
df = users.copy()
df.iloc[0]
df.iloc[0, 1]
df.iloc[5, 1] = 44
df.iloc[6, 1] = 30
df.iloc[7, 1] = 17
df.iloc[8, 1] = 18
df.iloc[9, 1] = 15
df.iloc[10, 1] = 23

for i in range(users.shape[0]):
    row = df.iloc[i]
    row.usia *=100 # setting a copy, and not the original frame data.
print(df)

C:\Users\iS\Anaconda3\lib\site-packages\pandas\core\generic.py:5096: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self[name] = value


        nama  usia kelamin  pekerjaan  tinggi
0     Ismail  18.0       L    pelajar     NaN
1    Fatimah  28.0       P    enginer     NaN
2       Musa  18.0       L  mahasiswa     NaN
3    Hidayah  28.0       P    manager     NaN
4   Sulaiman  30.0       L   engineer     NaN
5      Julie  44.0       P  scientist     NaN
6      Widya  30.0       P  scientist     NaN
7      Cindy  17.0       P   engineer     NaN
8     Jibril  18.0     NaN        NaN   165.0
9        Nur  15.0     NaN        NaN   180.0
10     Hilmy  23.0     NaN        NaN   165.0
11      Peny   NaN     NaN        NaN   170.0
12     Rindi   NaN     NaN        NaN   160.0
13      Arum   NaN     NaN        NaN   166.0
14      Agus   NaN     NaN        NaN   165.0


> ix supports mixed integer and label based access.

In [137]:
import sys

df = users.copy()
df.ix[0]
df.ix[0, 'usia']
df.ix[0, 'usia'] = 33

for i in range(df.shape[0]):
    df.ix[i, 'usia'] *= 10
print(df)

        nama   usia kelamin  pekerjaan  tinggi
0     Ismail  330.0       L    pelajar     NaN
1    Fatimah  280.0       P    enginer     NaN
2       Musa  180.0       L  mahasiswa     NaN
3    Hidayah  280.0       P    manager     NaN
4   Sulaiman  300.0       L   engineer     NaN
5      Julie  440.0       P  scientist     NaN
6      Widya  240.0       P  scientist     NaN
7      Cindy  260.0       P   engineer     NaN
8     Jibril    NaN     NaN        NaN   165.0
9        Nur    NaN     NaN        NaN   180.0
10     Hilmy    NaN     NaN        NaN   165.0
11      Peny    NaN     NaN        NaN   170.0
12     Rindi    NaN     NaN        NaN   160.0
13      Arum    NaN     NaN        NaN   166.0
14      Agus    NaN     NaN        NaN   165.0


C:\Users\iS\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  after removing the cwd from sys.path.
C:\Users\iS\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """
C:\Users\iS\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  
C:\Users\iS\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: DeprecationWa

### Rows selection (filtering)

> simple logical filtering

In [138]:
users[users.usia < 20]

nama  usia kelamin  pekerjaan  tinggi
0  Ismail  18.0       L    pelajar     NaN
2    Musa  18.0       L  mahasiswa     NaN

In [139]:
muda_bool = users.usia > 17
muda = users[muda_bool]
muda

nama  usia kelamin  pekerjaan  tinggi
0    Ismail  18.0       L    pelajar     NaN
1   Fatimah  28.0       P    enginer     NaN
2      Musa  18.0       L  mahasiswa     NaN
3   Hidayah  28.0       P    manager     NaN
4  Sulaiman  30.0       L   engineer     NaN
5     Julie  44.0       P  scientist     NaN
6     Widya  24.0       P  scientist     NaN
7     Cindy  26.0       P   engineer     NaN

In [140]:
users[users.usia < 17].pekerjaan
print(muda)

       nama  usia kelamin  pekerjaan  tinggi
0    Ismail  18.0       L    pelajar     NaN
1   Fatimah  28.0       P    enginer     NaN
2      Musa  18.0       L  mahasiswa     NaN
3   Hidayah  28.0       P    manager     NaN
4  Sulaiman  30.0       L   engineer     NaN
5     Julie  44.0       P  scientist     NaN
6     Widya  24.0       P  scientist     NaN
7     Cindy  26.0       P   engineer     NaN


> Advanced logical filtering

In [141]:
users[users.usia < 20][['usia','pekerjaan']]

usia  pekerjaan
0  18.0    pelajar
2  18.0  mahasiswa

In [142]:
users[(users.usia > 20) & (users.kelamin == 'P')]

nama  usia kelamin  pekerjaan  tinggi
1  Fatimah  28.0       P    enginer     NaN
3  Hidayah  28.0       P    manager     NaN
5    Julie  44.0       P  scientist     NaN
6    Widya  24.0       P  scientist     NaN
7    Cindy  26.0       P   engineer     NaN

In [143]:
users[users.pekerjaan.isin(['mahasiswa','enginer'])]

nama  usia kelamin  pekerjaan  tinggi
1  Fatimah  28.0       P    enginer     NaN
2     Musa  18.0       L  mahasiswa     NaN

### Sorting

In [144]:
df = users.copy()

df.usia.sort_values() # only works for a Series
df.sort_values(by='usia') # sort rows by a specific column
df.sort_values(by='usia', ascending=False) # use descending order instead
df.sort_values(by=['pekerjaan','usia']) # sort by multiple columns
df.sort_values(by=['pekerjaan', 'usia'], inplace=True) # modify df

df.head()

nama  usia kelamin  pekerjaan  tinggi
7     Cindy  26.0       P   engineer     NaN
4  Sulaiman  30.0       L   engineer     NaN
1   Fatimah  28.0       P    enginer     NaN
2      Musa  18.0       L  mahasiswa     NaN
3   Hidayah  28.0       P    manager     NaN

### Descriptive statistics

In [145]:
print(df.describe())

           usia      tinggi
count   8.00000    7.000000
mean   27.00000  167.285714
std     8.21149    6.317022
min    18.00000  160.000000
25%    22.50000  165.000000
50%    27.00000  165.000000
75%    28.50000  168.000000
max    44.00000  180.000000


> Summarize all columns

In [146]:
print(df.describe(include='all'))

        nama      usia kelamin pekerjaan      tinggi
count     15   8.00000       8         8    7.000000
unique    15       NaN       2         6         NaN
top     Musa       NaN       P  engineer         NaN
freq       1       NaN       5         2         NaN
mean     NaN  27.00000     NaN       NaN  167.285714
std      NaN   8.21149     NaN       NaN    6.317022
min      NaN  18.00000     NaN       NaN  160.000000
25%      NaN  22.50000     NaN       NaN  165.000000
50%      NaN  27.00000     NaN       NaN  165.000000
75%      NaN  28.50000     NaN       NaN  168.000000
max      NaN  44.00000     NaN       NaN  180.000000


In [147]:
print(df.describe(include=['object'])) # limit to one (or more) types

        nama kelamin pekerjaan
count     15       8         8
unique    15       2         6
top     Musa       P  engineer
freq       1       5         2


> Statistics per group (groupby)

In [148]:
print(df.groupby('pekerjaan').mean())

           usia  tinggi
pekerjaan              
engineer   28.0     NaN
enginer    28.0     NaN
mahasiswa  18.0     NaN
manager    28.0     NaN
pelajar    18.0     NaN
scientist  34.0     NaN


In [149]:
print(df.groupby('pekerjaan')['usia'].mean())

pekerjaan
engineer     28.0
enginer      28.0
mahasiswa    18.0
manager      28.0
pelajar      18.0
scientist    34.0
Name: usia, dtype: float64


In [153]:
print(df.groupby('pekerjaan').describe(include='all'))

           nama                                                      ...  \
          count unique       top freq mean  std  min  25%  50%  75%  ...   
pekerjaan                                                            ...   
engineer      2      2  Sulaiman    1  NaN  NaN  NaN  NaN  NaN  NaN  ...   
enginer       1      1   Fatimah    1  NaN  NaN  NaN  NaN  NaN  NaN  ...   
mahasiswa     1      1      Musa    1  NaN  NaN  NaN  NaN  NaN  NaN  ...   
manager       1      1   Hidayah    1  NaN  NaN  NaN  NaN  NaN  NaN  ...   
pelajar       1      1    Ismail    1  NaN  NaN  NaN  NaN  NaN  NaN  ...   
scientist     2      2     Widya    1  NaN  NaN  NaN  NaN  NaN  NaN  ...   

          tinggi                                        
          unique top freq mean std min 25% 50% 75% max  
pekerjaan                                               
engineer     NaN NaN  NaN  NaN NaN NaN NaN NaN NaN NaN  
enginer      NaN NaN  NaN  NaN NaN NaN NaN NaN NaN NaN  
mahasiswa    NaN NaN  NaN  NaN

> Groupby in a loop

In [154]:
for grup, data in df.groupby('pekerjaan'):
    print(grup, data)

engineer        nama  usia kelamin pekerjaan  tinggi
7     Cindy  26.0       P  engineer     NaN
4  Sulaiman  30.0       L  engineer     NaN
enginer       nama  usia kelamin pekerjaan  tinggi
1  Fatimah  28.0       P   enginer     NaN
mahasiswa    nama  usia kelamin  pekerjaan  tinggi
2  Musa  18.0       L  mahasiswa     NaN
manager       nama  usia kelamin pekerjaan  tinggi
3  Hidayah  28.0       P   manager     NaN
pelajar      nama  usia kelamin pekerjaan  tinggi
0  Ismail  18.0       L   pelajar     NaN
scientist     nama  usia kelamin  pekerjaan  tinggi
6  Widya  24.0       P  scientist     NaN
5  Julie  44.0       P  scientist     NaN


## Quality check

### Remove duplicate data

In [155]:
# Series of booleans
df = users.append(df.iloc[0], ignore_index=True)
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15     True
dtype: bool


In [156]:
# count of duplicates
df.duplicated().sum()

1

In [162]:
#only show duplicates
df[df.duplicated()]

Empty DataFrame
Columns: [nama, usia, kelamin, pekerjaan, tinggi]
Index: []

In [163]:
# check a single column for duplicates
df.usia.duplicated()

0     False
1     False
2      True
3      True
4     False
5     False
6     False
7     False
8     False
9      True
10     True
11     True
12     True
13     True
14     True
Name: usia, dtype: bool

In [165]:
# specify columns for finding duplicates
df.duplicated(['usia', 'kelamin']).sum()

8

In [166]:
# drop duplicate rows
df = df.drop_duplicates()
df

nama  usia kelamin  pekerjaan  tinggi
0     Ismail  18.0       L    pelajar     NaN
1    Fatimah  28.0       P    enginer     NaN
2       Musa  18.0       L  mahasiswa     NaN
3    Hidayah  28.0       P    manager     NaN
4   Sulaiman  30.0       L   engineer     NaN
5      Julie  44.0       P  scientist     NaN
6      Widya  24.0       P  scientist     NaN
7      Cindy  26.0       P   engineer     NaN
8     Jibril   NaN     NaN        NaN   165.0
9        Nur   NaN     NaN        NaN   180.0
10     Hilmy   NaN     NaN        NaN   165.0
11      Peny   NaN     NaN        NaN   170.0
12     Rindi   NaN     NaN        NaN   160.0
13      Arum   NaN     NaN        NaN   166.0
14      Agus   NaN     NaN        NaN   165.0

### Missing data

In [167]:
df = users.copy()
# excludes missing values
df.describe(include='all')

nama      usia kelamin pekerjaan      tinggi
count     15   8.00000       8         8    7.000000
unique    15       NaN       2         6         NaN
top     Musa       NaN       P  engineer         NaN
freq       1       NaN       5         2         NaN
mean     NaN  27.00000     NaN       NaN  167.285714
std      NaN   8.21149     NaN       NaN    6.317022
min      NaN  18.00000     NaN       NaN  160.000000
25%      NaN  22.50000     NaN       NaN  165.000000
50%      NaN  27.00000     NaN       NaN  165.000000
75%      NaN  28.50000     NaN       NaN  168.000000
max      NaN  44.00000     NaN       NaN  180.000000

> find missing values in a Series

In [168]:
df.tinggi.isnull()

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7      True
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: tinggi, dtype: bool

In [169]:
df.tinggi.notnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13     True
14     True
Name: tinggi, dtype: bool

In [170]:
df[df.tinggi.notnull()]

nama  usia kelamin pekerjaan  tinggi
8   Jibril   NaN     NaN       NaN   165.0
9      Nur   NaN     NaN       NaN   180.0
10   Hilmy   NaN     NaN       NaN   165.0
11    Peny   NaN     NaN       NaN   170.0
12   Rindi   NaN     NaN       NaN   160.0
13    Arum   NaN     NaN       NaN   166.0
14    Agus   NaN     NaN       NaN   165.0

In [171]:
df.tinggi.isnull().sum()

8

> find missing values in a DataFrame

In [172]:
df.isnull()

nama   usia  kelamin  pekerjaan  tinggi
0   False  False    False      False    True
1   False  False    False      False    True
2   False  False    False      False    True
3   False  False    False      False    True
4   False  False    False      False    True
5   False  False    False      False    True
6   False  False    False      False    True
7   False  False    False      False    True
8   False   True     True       True   False
9   False   True     True       True   False
10  False   True     True       True   False
11  False   True     True       True   False
12  False   True     True       True   False
13  False   True     True       True   False
14  False   True     True       True   False

In [173]:
df.isnull().sum()

nama         0
usia         7
kelamin      7
pekerjaan    7
tinggi       8
dtype: int64

> Strategy 1: drop missing values

In [174]:
df.dropna()

Empty DataFrame
Columns: [nama, usia, kelamin, pekerjaan, tinggi]
Index: []

In [175]:
df.dropna(how='all')

nama  usia kelamin  pekerjaan  tinggi
0     Ismail  18.0       L    pelajar     NaN
1    Fatimah  28.0       P    enginer     NaN
2       Musa  18.0       L  mahasiswa     NaN
3    Hidayah  28.0       P    manager     NaN
4   Sulaiman  30.0       L   engineer     NaN
5      Julie  44.0       P  scientist     NaN
6      Widya  24.0       P  scientist     NaN
7      Cindy  26.0       P   engineer     NaN
8     Jibril   NaN     NaN        NaN   165.0
9        Nur   NaN     NaN        NaN   180.0
10     Hilmy   NaN     NaN        NaN   165.0
11      Peny   NaN     NaN        NaN   170.0
12     Rindi   NaN     NaN        NaN   160.0
13      Arum   NaN     NaN        NaN   166.0
14      Agus   NaN     NaN        NaN   165.0

> Strategy 2: fill in missing values

In [176]:
df.tinggi.mean()

167.28571428571428

In [181]:
df = users.copy()
df.ix[df.tinggi.isnull(), 'tinggi'] = df['tinggi'].mean
print(df)

        nama  usia kelamin  pekerjaan  \
0     Ismail  18.0       L    pelajar   
1    Fatimah  28.0       P    enginer   
2       Musa  18.0       L  mahasiswa   
3    Hidayah  28.0       P    manager   
4   Sulaiman  30.0       L   engineer   
5      Julie  44.0       P  scientist   
6      Widya  24.0       P  scientist   
7      Cindy  26.0       P   engineer   
8     Jibril   NaN     NaN        NaN   
9        Nur   NaN     NaN        NaN   
10     Hilmy   NaN     NaN        NaN   
11      Peny   NaN     NaN        NaN   
12     Rindi   NaN     NaN        NaN   
13      Arum   NaN     NaN        NaN   
14      Agus   NaN     NaN        NaN   

                                               tinggi  
0   <bound method Series.mean of 0       NaN\n1   ...  
1   <bound method Series.mean of 0       NaN\n1   ...  
2   <bound method Series.mean of 0       NaN\n1   ...  
3   <bound method Series.mean of 0       NaN\n1   ...  
4   <bound method Series.mean of 0       NaN\n1   ...  
5   <bo

C:\Users\iS\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  


### Rename values

In [186]:
df = users.copy()
print(df.columns)

Index(['nama', 'usia', 'kelamin', 'pekerjaan', 'tinggi'], dtype='object')


## Dealing with outliers

In [188]:
size = pd.Series(np.random.normal(loc=175, size=20, scale=10))
size[:3] +=500
size

0     696.534224
1     683.691227
2     662.834962
3     177.312736
4     153.751353
5     172.496568
6     187.191086
7     200.023721
8     171.328810
9     184.703451
10    167.631936
11    176.631678
12    157.860084
13    180.769152
14    167.309040
15    152.125427
16    171.662915
17    185.157896
18    169.051147
19    195.944754
dtype: float64

### Based on parametric statistics: use the mean

> Normal distribution Exclude data outside 3 standard-deviations

In [189]:
size_outlr_mean = size.copy()
size_outlr_mean[((size - size.mean()).abs() > 3 * size.std())] = size.mean()
print(size_outlr_mean.mean())

250.70060819628557


### Based on non-parametric statistics: use the median

> Median absolute deviation (MAD)

In [191]:
mad = 1.4826 * np.median(np.abs(size - size.median()))
mad

14.087248732984557

In [192]:
size_outlr_mad = size.copy()
size_outlr_mad[((size - size.median()).abs() > 3 * mad)] = size.median()
print(size_outlr_mad.mean(), size_outlr_mad.median())

175.09341862566868 176.8019426598305


## File I/O

### csv

In [206]:
import tempfile, os.path

tmpdir = tempfile.gettempdir()
csv_filename = os.path.join(tmpdir, 'users.csv')
users.to_csv(csv_filename, index=False)
other = pd.read_csv(csv_filename)

> C:\Users\iS\AppData\Local\Temp\users.csv

### Read csv from url

In [274]:
url = 'https://raw.githubusercontent.com/peny77/Statistics-and-Machine-Learning-in-Python/master/users.csv'
mobil = pd.read_csv(url)
mobil.head()

nama  usia kelamin  pekerjaan  tinggi
0    Ismail  18.0       L    pelajar     NaN
1   Fatimah  28.0       P    enginer     NaN
2      Musa  18.0       L  mahasiswa     NaN
3   Hidayah  28.0       P    manager     NaN
4  Sulaiman  30.0       L   engineer     NaN

### Excel

In [281]:
xls_filename = os.path.join(tmpdir, 'users.xlsx')
users.to_excel(xls_filename, sheet_name='users', index=False)

pd.read_excel(xls_filename, sheetname='users')

# Multiple sheets
with pd.ExcelWriter(xls_filename) as writer:
    users.to_excel(writer, sheet_name='users', index=False)
    df.to_excel(writer, sheet_name='salary', index=False)
    
pd.read_excel(xls_filename, sheetname='users')
pd.read_excel(xls_filename, sheetname='salary')

nama  usia kelamin  pekerjaan  tinggi
0     Ismail  18.0       L    pelajar     NaN
1    Fatimah  28.0       P    enginer     NaN
2       Musa  18.0       L  mahasiswa     NaN
3    Hidayah  28.0       P    manager     NaN
4   Sulaiman  30.0       L   engineer     NaN
5      Julie  44.0       P  scientist     NaN
6      Widya  24.0       P  scientist     NaN
7      Cindy  26.0       P   engineer     NaN
8     Jibril   NaN     NaN        NaN   165.0
9        Nur   NaN     NaN        NaN   180.0
10     Hilmy   NaN     NaN        NaN   165.0
11      Peny   NaN     NaN        NaN   170.0
12     Rindi   NaN     NaN        NaN   160.0
13      Arum   NaN     NaN        NaN   166.0
14      Agus   NaN     NaN        NaN   165.0

### SQL (SQLite)

In [284]:
import pandas as pd
import sqlite3

db_filename = os.path.join(tmpdir, 'usersql.db')

> Connect

In [285]:
con = sqlite3.connect(db_filename)

> Creating tables with pandas

In [286]:
url = 'https://raw.githubusercontent.com/peny77/Statistics-and-Machine-Learning-in-Python/master/salary_table.csv'
salary = pd.read_csv(url)
salary.to_sql('salary', con, if_exists='replace')
salary.head()

salary  experience education management
0   13876           1  Bachelor          Y
1   11608           1      Ph.D          N
2   18701           1      Ph.D          Y
3   11283           1    Master          N
4   11767           1      Ph.D          N

> Push modifications

In [288]:
cur = con.cursor()
values = (46, 14000, 3, 'Master', 'N')
cur.execute('insert into salary values (?,?,?,?,?)', values)
con.commit()

> Reading results into a pandas DataFrame

In [291]:
salary_sql = pd.read_sql_query('select * from salary', con)
print(salary_sql.head())

   index  salary  experience education management
0      0   13876           1  Bachelor          Y
1      1   11608           1      Ph.D          N
2      2   18701           1      Ph.D          Y
3      3   11283           1    Master          N
4      4   11767           1      Ph.D          N


In [292]:
pd.read_sql_query('select * from salary', con).tail()

index  salary  experience education management
42     42   18838          16    Master          N
43     43   17483          16  Bachelor          N
44     44   19207          17    Master          N
45     45   19346          20  Bachelor          N
46     46   14000           3    Master          N

In [293]:
pd.read_sql_query('select * from salary where salary>25000', con)

index  salary  experience education management
0     33   25410          11    Master          Y
1     38   26330          13    Master          Y
2     40   25685          15      Ph.D          Y
3     41   27837          16    Master          Y

In [294]:
pd.read_sql_query('select * from salary where experience=16', con)

index  salary  experience education management
0     41   27837          16    Master          Y
1     42   18838          16    Master          N
2     43   17483          16  Bachelor          N

In [296]:
pd.read_sql_query('select * from salary where education="Master"', con)

index  salary  experience education management
0       3   11283           1    Master          N
1       5   20872           2    Master          Y
2       6   11772           2    Master          N
3       9   12313           3    Master          N
4      11   21371           3    Master          Y
5      16   12884           4    Master          N
6      17   13245           5    Master          N
7      22   13839           6    Master          N
8      23   22884           6    Master          Y
9      25   14803           8    Master          N
10     30   15942          10    Master          N
11     32   23780          10    Master          Y
12     33   25410          11    Master          Y
13     35   16882          12    Master          N
14     38   26330          13    Master          Y
15     39   17949          14    Master          N
16     41   27837          16    Master          Y
17     42   18838          16    Master          N
18     44   19207          17    Master          N
19     46   14000           3    Master          N